# -------------------- Import Modules --------------------
import glob
import logging
import os
import time

from Cornus.Data_Hunter.HuntingDataCore import HuntingDataCore
from Cornus.MetaUnits.VisionCore import VisionCore
from Hermes.ML_ClusterBox.Agglomerative_Cluster import Agglomerative_Cluster
from Hermes.ML_ClusterBox.DBSCAN_Cluster import DBSCAN_Cluster
from Hermes.ML_ClusterBox.KMean_Cluster import KMeans_Cluster
from Hermes.ML_UnSup_BaseConfigBox.UnSup_InputCore import UnSupInputCore

project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
report_root = os.path.join(project_root, "ML_Report")
save_dir = os.path.join(report_root, "Cluster_Profile_Report")

os.makedirs(save_dir, exist_ok=True)

logger = logging.getLogger("Hermes")
# -------------------- Model categories --------------------
MODEL_REGISTRY = {
    "KMeans": {
        "class": KMeans_Cluster,
        "task_type": "clustering",
    },
    "DBSCAN": {
        "class": DBSCAN_Cluster,
        "task_type": "clustering",
    },
    "AgglomerativeClustering": {
        "class": Agglomerative_Cluster,
        "task_type": "clustering",
    },
}


# -------------------- Hermes Engine --------------------
class HermesEngine:
    """
    Central orchestration engine for Hermes unsupervised clustering workflows.

    ``HermesEngine`` is the top-level controller that coordinates dataset
    loading, pipeline-core creation, input-column selection, clustering input
    construction, model creation, clustering execution, evaluation access, and
    trained-model persistence across the Hermes project.

    The engine is designed for terminal-based interactive workflows where a
    single engine instance is reused throughout the whole session. This allows
    loaded source data, selected input columns, built clustering data, current
    model state, clustering summaries, and saved-model operations to remain
    available across multiple menu actions.

    Main Responsibilities
    ---------------------
    The engine is responsible for:

    - loading a source dataset through ``HuntingDataCore``
    - building dependent workflow cores such as ``VisionCore`` and
      ``UnSupInputCore``
    - selecting unsupervised-learning input columns
    - building clustering feature data ``X``
    - listing available clustering models
    - constructing clustering model instances
    - dispatching clustering execution to model-specific engines
    - recording clustering outputs and summaries
    - exposing evaluation results and model-specific methods
    - saving trained clustering models to disk
    - loading trained clustering models from disk

    Workflow Overview
    -----------------
    1. Load a dataset into the engine.
    2. Build dependent cores based on the loaded source data.
    3. Select input columns for clustering.
    4. Build clustering input data ``X``.
    5. Create and run a clustering model.
    6. Store clustering outputs and summaries in engine state.
    7. Review evaluation results or visualization outputs.
    8. Save or reload trained clustering models when needed.

    Attributes
    ----------
    hunter_core : HuntingDataCore
        Core object responsible for folder searching, file searching, and
        opening source datasets.
    vision_core : VisionCore or None
        Optional inspection core built after source data is loaded.
    input_core : UnSupInputCore or None
        Input preparation core used to manage input-column selection and build
        unsupervised feature data.
    numeric_columns : object or None
        Reserved attribute for tracking numeric input columns.
    categorical_columns : object or None
        Reserved attribute for tracking categorical input columns.
    cluster_input_data : object or None
        Current clustering feature dataset built from selected input columns.
    current_model : object or None
        Current clustering model instance.
    current_model_name : str or None
        Name of the currently active clustering model.
    current_model_result : dict or object or None
        Latest result returned by the executed clustering engine.
    current_cluster_labels : object or None
        Cluster labels generated by the current model, if available.
    current_cluster_summary : dict or None
        Summary dictionary describing the current clustering run.
    current_cluster_preview : object or None
        Preview table or clustered-data snapshot, if provided by the model.
    current_cluster_size_summary : object or None
        Cluster-size summary, if provided by the model.

    Notes
    -----
    - This engine assumes that clustering models are registered in
      ``MODEL_REGISTRY``.
    - Loading a trained model requires clustering input data to already exist,
      because the base load workflow rebuilds transformed data and cluster
      outputs from the current input data.
    - Model save and load folders are managed centrally by the engine rather
      than by each clustering model class.
    """

    # -------------------- Initialization --------------------
    def __init__(self):
        """
        Initialize the Hermes unsupervised clustering engine.

        This constructor creates the data-loading core immediately and initializes
        all engine-level runtime attributes used during the clustering workflow.
        Pipeline-dependent cores such as ``VisionCore`` and ``UnSupInputCore`` are
        created later, after source data has been successfully loaded.

        Initialization State
        --------------------
        - ``hunter_core`` is created immediately
        - ``vision_core`` is initialized as ``None``
        - ``input_core`` is initialized as ``None``
        - input-column and clustering-data records are empty
        - current model and result records are empty
        - cluster summary and preview records are empty

        Returns
        -------
        None

        Notes
        -----
        This method does not load any dataset automatically. It only prepares the
        engine so later menu actions can build the workflow step by step.
        """
        # ---------- Cores ----------
        self.hunter_core = HuntingDataCore()
        self.vision_core = None
        self.input_core = None

        # ---------- Record cluster data / columns ----------
        self.numeric_columns = None
        self.categorical_columns = None
        self.cluster_input_data = None

        # ---------- Record current model and results ----------
        self.current_model = None
        self.current_model_name = None
        self.current_model_result = None

        # ---------- Record cluster information ----------
        self.current_cluster_labels = None
        self.current_cluster_summary = None
        self.current_cluster_profile_summary = None
        self.current_cluster_preview = None
        self.current_cluster_size_summary = None
        logger.info("HermesEngine initialized")

    # -------------------- Source data property --------------------
    @property
    def source_data(self):
        """
        Return the current source dataset stored in the data-loading core.

        This property exposes ``self.hunter_core.target_data`` as a direct engine
        attribute so the rest of the Hermes workflow can read the currently loaded
        dataset without accessing the loader core manually.

        Returns
        -------
        object
            Current source dataset stored in ``HuntingDataCore``. In typical use,
            this is expected to be a pandas ``DataFrame``, though the exact type
            depends on the data-opening implementation.

        Notes
        -----
        This property is read-only from the engine interface perspective. Source
        data changes should happen through the dataset-loading workflow.
        """
        return self.hunter_core.target_data

    # -------------------- Build pipeline cores --------------------
    def build_cores(self):
        """
        Build all pipeline-dependent cores required for the Hermes workflow.

        This method creates the downstream helper cores that depend on the currently
        loaded source dataset. It constructs ``VisionCore`` for inspection-related
        operations and ``UnSupInputCore`` for clustering input selection and
        unsupervised feature construction.

        Returns
        -------
        None

        Raises
        ------
        ValueError
            Raised when no source dataset is currently available.

        Workflow
        --------
        1. Check whether source data is loaded.
        2. Create ``VisionCore`` from the current loader core.
        3. Create ``UnSupInputCore`` from the current source dataset.
        4. Store the created cores in engine state.

        Notes
        -----
        This method must be called only after a dataset has been loaded
        successfully.
        """
        logger.info("Building Hermes pipeline cores")

        if self.source_data is None:
            logger.warning("build_cores failed: source_data is None")
            raise ValueError("⚠️ No source data available. Please load data first ‼️")

        self.vision_core = VisionCore(self.hunter_core)
        self.input_core = UnSupInputCore(self.source_data)
        logger.info(
            "Pipeline cores built successfully: vision_core=%s, input_core=%s",
            self.vision_core is not None,
            self.input_core is not None,
        )

    # -------------------- Refresh all pipeline cores (Changing another dataset) --------------------
    def refresh_cores(self):
        """
        Rebuild all pipeline-dependent cores using the current source dataset.

        This method is intended for workflows where the loaded dataset has changed
        and the dependent cores must be reconstructed so that they operate on the
        latest source data.

        Returns
        -------
        None

        Notes
        -----
        This method delegates directly to ``build_cores()`` and therefore carries
        the same requirement that source data must already exist.
        """
        logger.info("Refreshing Hermes pipeline cores")

        self.build_cores()
        logger.info("Hermes pipeline cores refreshed successfully")

    # -------------------- ML dataset searching --------------------
    def ml_dataset_search(
        self,
        selected_folder_num: int,
        selected_file_num: int,
        opener_param_dict: dict | None = None,
    ):
        """
        Search for, open, and register a machine-learning dataset.

        This method coordinates the dataset-loading workflow by searching available
        folders, locating the selected file, opening it through
        ``HuntingDataCore``, and building dependent cores when loading succeeds.

        Parameters
        ----------
        selected_folder_num : int
            Numeric folder selection used by the working-place search workflow.
        selected_file_num : int
            Numeric file selection inside the chosen folder.
        opener_param_dict : dict or None, default=None
            Optional keyword-argument dictionary passed to the dataset opener.

        Returns
        -------
        object or None
            Loaded dataset if opening succeeds; otherwise ``None``.

        Workflow
        --------
        1. Search available folders in the working place.
        2. Search files inside the selected folder.
        3. Open the target dataset.
        4. Build dependent cores if the dataset is loaded successfully.
        5. Return the loaded dataset.

        Notes
        -----
        If ``opener_param_dict`` is omitted, an empty dictionary is used.
        """
        logger.info(
            "Starting dataset search: folder_num=%s, file_num=%s",
            selected_folder_num,
            selected_file_num,
        )

        # ---------- Searching folder and file ----------
        self.hunter_core.working_place_searcher()
        self.hunter_core.files_searcher_from_folders(
            selected_folder_num=selected_folder_num,
            selected_file_num=selected_file_num,
        )

        # ---------- Opening target data ----------
        opener_param_dict = opener_param_dict or {}
        loaded_data = self.hunter_core.opener(**opener_param_dict)
        logger.info("Dataset opener parameters: %s", opener_param_dict)

        if loaded_data is not None:
            self.build_cores()
            logger.info("Dependent cores built after dataset loading")
        else:
            logger.warning("Dataset loading failed")

        return loaded_data

    # -------------------- Set input columns --------------------
    def set_input_columns(self, input_columns: list[str]):
        """
        Set clustering input columns in the unsupervised input core.

        This method forwards the selected input-column list to
        ``UnSupInputCore`` so that the clustering workflow knows which source-data
        columns should be used to build the unsupervised feature dataset.

        Parameters
        ----------
        input_columns : list[str]
            Column names selected for clustering input.

        Returns
        -------
        object or None
            Return value from ``self.input_core.set_input_columns(input_columns)``,
            or ``None`` when the input core has not yet been built.

        Notes
        -----
        This method requires ``self.input_core`` to exist before it can run.
        """
        logger.info("Setting input columns: %s", input_columns)
        if self.input_core is None:
            logger.warning("set_input_columns failed: input_core is None")
            print("⚠️ InputCore has not been built ‼️")
            return None

        result = self.input_core.set_input_columns(input_columns)
        logger.info("Input columns set successfully")
        return result

    # -------------------- Build X data --------------------
    def build_x_data(self):
        """
        Build and store clustering feature data from the selected input columns.

        This method requests ``UnSupInputCore`` to construct the unsupervised
        feature dataset ``X`` from the currently selected input columns. The
        resulting dataset is stored in ``self.cluster_input_data`` and also
        returned.

        Returns
        -------
        object or None
            Built clustering feature dataset if successful; otherwise ``None`` when
            the input core has not been built or when feature construction fails.

        Notes
        -----
        The exact return type depends on the implementation of
        ``UnSupInputCore.build_x_data()``.
        """
        logger.info("Building clustering X data")

        if self.input_core is None:
            logger.warning("build_x_data failed: input_core is None")
            print("⚠️ InputCore has not been built ‼️")
            return None

        self.cluster_input_data = (
            self.input_core.build_x_data()
        )  # Return X from UnSupInoutCore
        if self.cluster_input_data is None:
            logger.warning("build_x_data failed: input_core.build_x_data returned None")
            return None

        logger.info(
            "Clustering X data built successfully with shape=%s",
            getattr(self.cluster_input_data, "shape", None),
        )

        return self.cluster_input_data  # Record by Hermes instance

    # -------------------- Reset feature selection --------------------
    def reset_input_selection(self):
        """
        Reset the current clustering input-selection state.

        This method clears the selected input-column state stored in
        ``UnSupInputCore`` and also resets the engine-level cached clustering input
        dataset.

        Returns
        -------
        None

        Notes
        -----
        If the input core has not been built, the method returns ``None`` after
        showing a warning message.
        """
        logger.info("Resetting input selection")
        if self.input_core is None:
            logger.warning("reset_input_selection failed: input_core is None")
            print("⚠️ InputCore has not been built ‼️")
            return None

        self.input_core.reset_input_state()
        self.cluster_input_data = None
        logger.info("Input selection reset successfully")

    # -------------------- Input data selection --------------------
    def select_input_data(
        self,
        input_columns: list[str] | None = None,
    ):
        """
        Set clustering input columns and build clustering feature data.

        This helper combines two common unsupervised-workflow steps into one method:
        optionally setting input columns and then building the corresponding
        clustering feature dataset ``X``.

        Parameters
        ----------
        input_columns : list[str] or None, default=None
            Column names to set before building clustering feature data. If
            ``None``, the method skips the assignment step and directly attempts to
            build ``X`` using the current input-core state.

        Returns
        -------
        object or None
            Built clustering feature dataset if successful; otherwise ``None``.

        Workflow
        --------
        1. Confirm that the input core exists.
        2. If input columns are provided, set them first.
        3. Build clustering feature data ``X``.
        4. Return the built dataset.

        Notes
        -----
        This method is convenient for terminal menus that want to complete input
        selection and feature construction in a single step.
        """
        logger.info("Selecting input data with input_columns=%s", input_columns)

        if self.input_core is None:
            logger.warning("select_input_data failed: input_core is None")
            print("⚠️ InputCore has not been built ‼️")
            return None

        if input_columns is not None:
            input_result = self.set_input_columns(
                input_columns
            )  # Give input columns to Hermes's set_input_columns method
            if input_result is None:
                logger.warning("select_input_data failed while setting input columns")
                return None

        result = self.build_x_data()
        if result is None:
            logger.warning("select_input_data failed while building X data")
            return None

        logger.info("Input data selection completed successfully")
        return result

    # -------------------- Current input selections --------------------
    def show_current_input_selection(self):
        """
        Display the current clustering input selection and built feature-data shape.

        This method prints the number of selected input columns, the selected
        column names, and the shape of the built clustering feature dataset stored
        inside ``UnSupInputCore``.

        Returns
        -------
        None

        Notes
        -----
        - If the input core does not exist, the method prints a warning and returns.
        - If no input columns are selected, the display shows zero inputs.
        - If ``X`` has not been built yet, the display shows no shape information.
        """
        logger.info("Showing current input selection")

        if self.input_core is None:
            logger.warning("show_current_input_selection failed: input_core is None")
            print("⚠️ UnSupInputCore is not available ‼️")
            return None

        if self.input_core.input_columns is None:
            print("🔥 Input count : 0")
            print(f"🔥 Input columns: None\n{'-'*100}")
        else:
            print(f"🔥 Input count : {len(self.input_core.input_columns)}")
            print(f"🔥 Input columns: {self.input_core.input_columns}\n{'-'*100}")

        if self.input_core.X is None:
            print(f"🔥 X shape: None\n{'-'*100}")
        else:
            print(f"🔥 X shape: {self.input_core.X.shape}\n{'-'*100}")

    # -------------------- Get models --------------------
    def get_available_models(self, task_type: str | None = None) -> list[str]:
        """
        Return available model names registered in the Hermes model registry.

        This method lists model names from ``MODEL_REGISTRY``. When a task type is
        provided, only models matching that task type are returned.

        Parameters
        ----------
        task_type : str or None, default=None
            Task category used to filter available model names. If ``None``, all
            registered model names are returned.

        Returns
        -------
        list[str]
            List of available model names.

        Notes
        -----
        In the current registry design, Hermes clustering models use the task type
        ``"clustering"``.
        """
        logger.info("Getting available models with task_type=%s", task_type)

        if task_type is None:
            models = list(MODEL_REGISTRY.keys())
        else:
            models = [
                model_name
                for model_name, meta in MODEL_REGISTRY.items()
                if meta["task_type"] == task_type
            ]

        logger.info("Available model count: %s", len(models))
        return models

    # -------------------- Build model instance --------------------
    def build_model(self, model_name: str):
        """
        Build and register a clustering model instance for the current feature data.

        This method validates that the input core and clustering feature dataset
        already exist, resolves the requested model class from ``MODEL_REGISTRY``,
        creates the model instance, and stores it as the current active model.

        Parameters
        ----------
        model_name : str
            Name of the clustering model to build.

        Returns
        -------
        object or None
            Newly created clustering model instance if successful; otherwise
            ``None`` when validation fails or the model name is unsupported.

        Workflow
        --------
        1. Confirm that the input core exists.
        2. Confirm that clustering feature data ``X`` has already been built.
        3. Resolve model metadata from the registry.
        4. Create the model instance using the current feature dataset.
        5. Record the model as the current active model.
        6. Reset the current model-result cache.

        Notes
        -----
        The model instance is built using ``self.input_core.X`` as the cleaned
        clustering input data.
        """
        logger.info("Building model instance for model_name=%s", model_name)

        if self.input_core is None:
            logger.warning("build_model failed: input_core is None")
            print("⚠️ InputCore has not been built ‼️")
            return None

        if self.input_core.X is None:
            logger.warning("build_model failed: X data has not been built")
            print("⚠️ X has not been built yet. Please select X data first ‼️")
            return None

        model_meta = MODEL_REGISTRY.get(model_name)
        if model_meta is None:
            logger.warning("build_model failed: unsupported model_name=%s", model_name)
            print(f"⚠️ Unsupported model type: {model_name} ‼️")
            return None

        model_cls = model_meta["class"]

        self.current_model = model_cls(cleaned_X_data=self.input_core.X)
        self.current_model_name = model_name
        self.current_model_result = None

        logger.info("Model instance built successfully: %s", model_name)
        print(f"🔥 Model instance built successfully: {model_name}\n{'-'*100}")
        return self.current_model

    # -------------------- Run clustering model --------------------
    def cluster_model(
        self,
        model_name: str,
        **cluster_kwargs,
    ):
        """
        Build and execute a clustering model, then record clustering results.

        This method creates the requested clustering model, dispatches execution to
        the model-specific clustering engine method, validates success, and records
        cluster-related outputs in engine state.

        Parameters
        ----------
        model_name : str
            Name of the clustering model to execute.
        **cluster_kwargs
            Model-specific keyword arguments forwarded to the corresponding
            clustering engine method.

        Returns
        -------
        dict or object or None
            Result returned by the clustering model engine if successful; otherwise
            ``None``.

        Workflow
        --------
        1. Build the requested model instance.
        2. Resolve clustering dispatch logic from the model name.
        3. Execute the model-specific clustering engine.
        4. Validate that clustering succeeds.
        5. Record clustering outputs and summaries in engine state.
        6. Return the clustering result.

        Notes
        -----
        Supported dispatch targets include:

        - ``kmeans_model_engine``
        - ``dbscan_model_engine``
        - ``agglomerative_model_engine``
        """
        logger.info(
            "Starting clustering: model_name=%s, cluster_kwargs=%s",
            model_name,
            cluster_kwargs,
        )

        model = self.build_model(model_name)
        if model is None:
            logger.warning(
                "cluster_model failed: build_model returned None for %s", model_name
            )
            return None

        model_meta = MODEL_REGISTRY.get(model_name)
        if model_meta is None:
            print(f"⚠️ Unsupported model type: {model_name} ‼️")
            return None

        logger.info("Dispatching clustering engine for model_name=%s", model_name)
        # ---------- Dispatch to model-specific engine ----------
        if model_name == "KMeans":
            result = model.kmeans_model_engine(**cluster_kwargs)

        elif model_name == "DBSCAN":
            result = model.dbscan_model_engine(**cluster_kwargs)

        elif model_name == "AgglomerativeClustering":
            result = model.agglomerative_model_engine(**cluster_kwargs)

        else:
            print(f"⚠️ No clustering engine defined for model: {model_name} ‼️")
            return None

        if result is None:
            logger.warning("Clustering execution failed for model_name=%s", model_name)
            print(f"⚠️ Failed to run clustering model: {model_name} ‼️")
            return None

        # ---------- Record current clustering results ----------
        self.current_model_result = result
        self.current_cluster_labels = getattr(model, "labels_", None)
        self.current_cluster_summary = result
        self.current_cluster_preview = getattr(model, "clustered_data_preview", None)
        self.current_cluster_size_summary = getattr(model, "cluster_size_summary", None)

        # ---------- Auto build and save cluster profile summary ----------
        try:
            logger.info(
                "Generating cluster profile summary automatically for model_name=%s",
                model_name,
            )
            model.cluster_profile_summary_engine()
            self.sync_current_cluster_profile_summary()
            self.save_current_cluster_profile_summary_csv()
            logger.info(
                "Cluster profile summary generated and saved automatically for model_name=%s",
                model_name,
            )
        except Exception as e:
            logger.warning(
                "Auto generation/saving of cluster profile summary failed for model_name=%s: %s",
                model_name,
                e,
            )

        logger.info("Clustering completed successfully for model_name=%s", model_name)
        return result

    # -------------------- Get current cluster evaluation --------------------
    def get_cluster_evaluation(self):
        """
        Return the evaluation result of the current clustering model.

        This method reads the ``evaluation_result`` attribute from the current model
        instance, if available.

        Returns
        -------
        object or None
            Current model evaluation result if available; otherwise ``None``.

        Notes
        -----
        If no current model exists yet, the method returns ``None`` after printing
        a warning message.
        """
        logger.info("Getting cluster evaluation")

        if self.current_model is None:
            logger.warning("get_cluster_evaluation failed: current_model is None")
            print("⚠️ No current model available yet ‼️")
            return None

        logger.info("Cluster evaluation fetched successfully")
        return getattr(self.current_model, "evaluation_result", None)

    # -------------------- Run current model method --------------------
    def run_current_model_method(self, method_name: str, **kwargs):
        """
        Execute a named method on the current active model.

        This helper allows dynamic access to model-specific methods after a model
        has been built or loaded. It validates that a current model exists, checks
        whether the requested attribute exists and is callable, and then executes it
        with the provided keyword arguments.

        Parameters
        ----------
        method_name : str
            Name of the method to execute on the current model.
        **kwargs
            Keyword arguments passed to the target method.

        Returns
        -------
        object or None
            Return value from the executed model method, or ``None`` when the
            current model is unavailable, the attribute does not exist, or the
            attribute is not callable.
        """
        logger.info(
            "Running current model method: %s with kwargs=%s", method_name, kwargs
        )

        if self.current_model is None:
            logger.warning("run_current_model_method failed: current_model is None")
            print("⚠️ No current model available ‼️")
            return None

        if not hasattr(self.current_model, method_name):
            logger.warning(
                "run_current_model_method failed: method not found: %s", method_name
            )
            print(f"⚠️ Current model does not support method: {method_name} ‼️")
            return None

        method = getattr(self.current_model, method_name)

        if not callable(method):
            logger.warning(
                "run_current_model_method failed: attribute not callable: %s",
                method_name,
            )
            print(f"⚠️ Attribute '{method_name}' is not callable ‼️")
            return None

        result = method(**kwargs)
        logger.info("Current model method executed successfully: %s", method_name)
        return result

    # -------------------- Show current cluster summary --------------------
    def show_current_model_summary(self):
        """
        Display a summary of the current clustering result.

        This method prints the main fields stored in
        ``self.current_cluster_summary``, including task name, sample count,
        cluster count, noise statistics, and feature-name count.

        Returns
        -------
        None

        Notes
        -----
        If no clustering summary is currently available, the method prints a
        warning and returns without further action.
        """
        logger.info("Showing current cluster summary")

        if self.current_cluster_summary is None:
            logger.warning(
                "show_current_model_summary failed: current_cluster_summary is None"
            )
            print("⚠️ No cluster summary available yet ‼️")
            return

        print(f"🪔 Current model : {self.current_model_name}")
        print(f"🪔 Task : {self.current_cluster_summary.get('task')}")
        print(f"🪔 Sample count : {self.current_cluster_summary.get('n_samples')}")
        print(
            f"🪔 Cluster count : {self.current_cluster_summary.get('n_clusters_found')}"
        )
        print(f"🪔 Noise count : {self.current_cluster_summary.get('noise_count')}")
        print(f"🪔 Noise ratio : {self.current_cluster_summary.get('noise_ratio')}")
        print(
            f"🪔 Feature names length : {self.current_cluster_summary.get('feature_names_len')}"
        )
        print(
            f"🪔 Cluster profile summary ready : "
            f"{self.current_cluster_profile_summary is not None}\n{'-'*100}"
        )
        logger.info(
            "Current cluster summary displayed for model_name=%s",
            self.current_model_name,
        )

    # -------------------- Show cluster profile summary --------------------
    def sync_current_cluster_profile_summary(self):
        """
        Synchronize the cluster profile summary from the current model to HermesEngine.

        This method reads the ``cluster_profile_summary`` attribute from the current
        active clustering model and stores it in
        ``self.current_cluster_profile_summary`` so the engine can reuse the profile
        summary for display, export, or later workflow steps.

        Returns
        -------
        None

        Notes
        -----
        - If ``self.current_model`` is ``None``, this method clears
        ``self.current_cluster_profile_summary`` and returns.
        - If the current model does not provide ``cluster_profile_summary``, the
        engine-level summary is set to ``None``.
        - When synchronization succeeds, the stored summary is expected to be a
        tabular object such as a pandas ``DataFrame``.
        """
        logger.info("Synchronizing current cluster profile summary from current model")

        if self.current_model is None:
            logger.warning(
                "sync_current_cluster_profile_summary failed: current_model is None"
            )
            self.current_cluster_profile_summary = None
            return

        self.current_cluster_profile_summary = getattr(
            self.current_model,
            "cluster_profile_summary",
            None,
        )

        if self.current_cluster_profile_summary is None:
            logger.info("No cluster profile summary found on current model")
        else:
            logger.info(
                "Cluster profile summary synchronized successfully: shape=%s",
                self.current_cluster_profile_summary.shape,
            )

    # -------------------- Save current cluster profile summary CSV --------------------
    def save_current_cluster_profile_summary_csv(self):
        """
        Automatically save current cluster profile summary to a CSV file.

        This method saves ``self.current_cluster_profile_summary`` into the
        Hermes report folder without asking the user for extra input.

        Returns
        -------
        None

        Notes
        -----
        - If no cluster profile summary is available, the method returns
          without saving.
        - The file is stored under:
          ``ML_Report/Cluster_Profile_Report``.
        - The file name includes the current model name and a timestamp.
        """
        logger.info("Saving current cluster profile summary CSV automatically")

        if self.current_cluster_profile_summary is None:
            logger.warning(
                "save_current_cluster_profile_summary_csv failed: "
                "current_cluster_profile_summary is None"
            )
            return

        model_name = self.current_model_name or "UnknownModel"
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        file_name = f"{model_name}_cluster_profile_summary_{timestamp}.csv"
        save_path = os.path.join(save_dir, file_name)

        self.current_cluster_profile_summary.to_csv(save_path, encoding="utf-8-sig")

        logger.info("Cluster profile summary CSV saved successfully: %s", save_path)
        print(f"🔥 Cluster profile summary saved successfully: {save_path}")

    # -------------------- Save current clustering model --------------------
    def save_current_model(self):
        """
        Save the current clustering model to its configured trained-model folder.

        This method validates that a current model exists, resolves the appropriate
        save folder from the current model name, creates the folder if necessary,
        builds a timestamped ``.joblib`` filename, and delegates the actual saving
        operation to the model's ``save_model_engine()`` method.

        Returns
        -------
        object or None
            Return value from ``self.current_model.save_model_engine(file_path)``,
            or ``None`` when saving cannot proceed.

        Workflow
        --------
        1. Confirm that a current model exists.
        2. Confirm that the current model name exists.
        3. Confirm that the model supports ``save_model_engine()``.
        4. Resolve the save folder from the model name.
        5. Create the target folder if needed.
        6. Build a timestamped joblib file path.
        7. Save the model through the model's save engine.

        Notes
        -----
        The engine manages save-folder routing centrally so all clustering models
        use a consistent trained-model folder structure.
        """
        logger.info("Saving current clustering model")

        if self.current_model is None:
            logger.warning("save_current_model failed: current_model is None")
            print("⚠️ No current model available ‼️")
            return None

        if self.current_model_name is None:
            logger.warning("save_current_model failed: current_model_name is None")
            print("⚠️ Current model name is missing ‼️")
            return None

        if not hasattr(self.current_model, "save_model_engine"):
            logger.warning("save_current_model failed: save_model_engine not supported")
            print("⚠️ Current model does not support save_model_engine() ‼️")
            return None

        folder_path = self._get_model_save_folder(self.current_model_name)
        if folder_path is None:
            logger.warning(
                "save_current_model failed: unsupported model_name=%s",
                self.current_model_name,
            )
            print("⚠️ Unsupported model type for saving ‼️")
            return None

        os.makedirs(folder_path, exist_ok=True)

        timestamp = time.strftime("%Y%m%d_%H%M%S")
        file_name = f"{self.current_model_name}_{timestamp}.joblib"
        file_path = os.path.join(folder_path, file_name)

        result = self.current_model.save_model_engine(file_path)

        logger.info(
            "Current clustering model saved successfully: model_name=%s, file_path=%s",
            self.current_model_name,
            file_path,
        )
        print(f"🔥 Model saved successfully: {file_path}")
        return result

    # -------------------- Helper: Get saved clustering model folder --------------------
    def _get_model_save_folder(self, model_name: str) -> str | None:
        """
        Return the trained-model save folder path for a given clustering model.

        This internal helper maps a clustering model name to its corresponding
        folder under the project ``ML_Report`` directory.

        Parameters
        ----------
        model_name : str
            Name of the clustering model.

        Returns
        -------
        str or None
            Folder path used for saving trained models of the given type, or
            ``None`` when the model name is unsupported.

        Notes
        -----
        Current folder mappings include:

        - ``KMeans`` -> ``KMean_Trained_Model``
        - ``DBSCAN`` -> ``DBSCAN_Trained_Model``
        - ``AgglomerativeClustering`` -> ``Agglomerative_Trained_Model``
        """
        logger.info("Resolving model save folder for model_name=%s", model_name)

        folder_map = {
            "KMeans": "KMean_Trained_Model",
            "DBSCAN": "DBSCAN_Trained_Model",
            "AgglomerativeClustering": "Agglomerative_Trained_Model",
        }

        folder_name = folder_map.get(model_name)
        if folder_name is None:
            logger.warning(
                "_get_model_save_folder failed: unsupported model_name=%s", model_name
            )
            return None

        folder_path = os.path.join(report_root, folder_name)
        logger.info("Resolved model save folder: %s", folder_path)
        return folder_path

    # -------------------- Helper: Get saved clustering model files --------------------
    def _get_saved_model_files(self, model_name: str) -> list[str]:
        """
        Return saved ``.joblib`` model files for a given clustering model type.

        This internal helper resolves the model-specific trained-model folder,
        searches it for ``.joblib`` files, sorts the files by modification time in
        descending order, and returns the resulting file list.

        Parameters
        ----------
        model_name : str
            Name of the clustering model whose saved files should be listed.

        Returns
        -------
        list[str]
            List of saved model file paths sorted from newest to oldest.

        Notes
        -----
        An empty list is returned when:

        - the model name is unsupported
        - the target save folder does not exist
        - no matching ``.joblib`` files are found
        """
        logger.info("Getting saved model files for model_name=%s", model_name)

        folder_path = self._get_model_save_folder(model_name)
        if folder_path is None:
            logger.warning(
                "_get_saved_model_files failed: unsupported model_name=%s", model_name
            )
            return []

        if not os.path.isdir(folder_path):
            logger.warning("Saved model folder not found: %s", folder_path)
            return []

        model_files = glob.glob(os.path.join(folder_path, "*.joblib"))
        model_files.sort(key=os.path.getmtime, reverse=True)

        logger.info(
            "Found %s saved model file(s) for model_name=%s",
            len(model_files),
            model_name,
        )
        return model_files

    # -------------------- Load saved clustering model --------------------
    def load_trained_model(self, model_name: str, filepath: str):
        """
        Load a trained clustering model from disk and register it as current.

        This method resolves the requested model class from ``MODEL_REGISTRY``,
        creates a model instance using the current clustering feature dataset, and
        restores the saved pipeline by calling the model's
        ``load_model_engine(filepath)`` method. After loading, it registers the
        loaded model as the current active model and synchronizes cluster-related
        runtime state back into the engine.

        Parameters
        ----------
        model_name : str
            Name of the clustering model type to load.
        filepath : str
            File path of the saved ``.joblib`` model file.

        Returns
        -------
        object or None
            Loaded model object if successful; otherwise ``None``.

        Workflow
        --------
        1. Validate that the requested model name exists in ``MODEL_REGISTRY``.
        2. Confirm that clustering input data already exists.
        3. Create a new model instance using the current clustering input data.
        4. Restore the saved trained pipeline through ``load_model_engine()``.
        5. Register the loaded model as the current active model.
        6. Synchronize evaluation, labels, summary, preview, size summary, and
        profile summary back into engine state.

        Notes
        -----
        - This method requires ``self.cluster_input_data`` to already be available,
        because the model load workflow rebuilds clustering runtime state from the
        current input data.
        - The loaded object is not used directly from disk as a standalone engine
        replacement; instead, a fresh model instance is created and then populated
        through its load workflow.
        - Cluster-related cached summaries are expected to be rebuilt by the model
        load workflow before synchronization into Hermes engine state.
        """
        logger.info(
            "Loading trained model: model_name=%s, filepath=%s",
            model_name,
            filepath,
        )

        model_meta = MODEL_REGISTRY.get(model_name)
        if model_meta is None:
            logger.warning(
                "load_trained_model failed: unsupported model_name=%s",
                model_name,
            )
            print(f"⚠️ Unsupported model type: {model_name} ‼️")
            return None

        if self.cluster_input_data is None:
            logger.warning("load_trained_model failed: cluster_input_data is None")
            print("⚠️ Cluster input data is missing. Build X data first ‼️")
            return None

        model_cls = model_meta["class"]

        try:
            loaded_model = model_cls(cleaned_X_data=self.cluster_input_data)

            if not hasattr(loaded_model, "load_model_engine"):
                logger.warning(
                    "load_trained_model failed: load_model_engine not supported for %s",
                    model_name,
                )
                print("⚠️ This model does not support load_model_engine() ‼️")
                return None

            loaded_model.load_model_engine(filepath)

        except Exception as e:
            logger.exception(
                "Failed to load model: model_name=%s, filepath=%s, error=%s",
                model_name,
                filepath,
                e,
            )
            print("⚠️ Failed to load model ‼️")
            return None

        if loaded_model is None:
            logger.warning("load_trained_model failed: loaded_model is None")
            print("⚠️ Loaded model is None ‼️")
            return None

        # ---------- Register loaded model ----------
        self.current_model = loaded_model
        self.current_model_name = model_name
        self.current_model_result = getattr(loaded_model, "evaluation_result", None)
        self.current_cluster_labels = getattr(loaded_model, "labels_", None)
        self.current_cluster_summary = getattr(loaded_model, "cluster_summary", None)
        self.current_cluster_preview = getattr(
            loaded_model, "clustered_data_preview", None
        )
        self.current_cluster_size_summary = getattr(
            loaded_model, "cluster_size_summary", None
        )
        self.current_cluster_profile_summary = getattr(
            loaded_model, "cluster_profile_summary", None
        )

        logger.info(
            "Loaded model runtime state synchronized: summary_ready=%s, preview_ready=%s, size_ready=%s, profile_ready=%s",
            self.current_cluster_summary is not None,
            self.current_cluster_preview is not None,
            self.current_cluster_size_summary is not None,
            self.current_cluster_profile_summary is not None,
        )

        logger.info(
            "Model loaded successfully: model_name=%s, filepath=%s",
            model_name,
            filepath,
        )
        print(f"🔥 Model loaded successfully: {filepath}")
        return loaded_model


# =================================================
